# Generated by Django 4.0.6 on 2022-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_pr',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='video_pr',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео'),
        ),
    ]
