# Generated by Django 4.0.6 on 2022-08-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_project_image_pr_project_video_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_pr',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
