# Generated by Django 4.0.6 on 2022-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_alter_project_image_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='objectlayout',
            name='layout',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото планировки'),
        ),
    ]
