# Generated by Django 4.0.6 on 2022-08-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Общая информация')),
                ('description_ru', models.TextField(null=True, verbose_name='Общая информация')),
                ('description_en', models.TextField(null=True, verbose_name='Общая информация')),
                ('tel_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тел_1')),
                ('tel_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тел_2')),
                ('tel_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тел_3')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Данные о компании',
                'verbose_name_plural': 'Данные о компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='Имя оставляющего отзыв')),
                ('name_user_ru', models.CharField(max_length=100, null=True, verbose_name='Имя оставляющего отзыв')),
                ('name_user_en', models.CharField(max_length=100, null=True, verbose_name='Имя оставляющего отзыв')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('review_ru', models.TextField(null=True, verbose_name='Отзыв')),
                ('review_en', models.TextField(null=True, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы о компании',
                'verbose_name_plural': 'Отзывы о компании',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО Сотрудника')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО Сотрудника')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО Сотрудника')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('job_title_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('job_title_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Краткая информация о сотруднике')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Краткая информация о сотруднике')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Краткая информация о сотруднике')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название новости')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Название новости')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Название новости')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Предоставляемые услуги',
                'verbose_name_plural': 'Предоставляемые услуги',
            },
        ),
    ]
